routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\ImageController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::middleware(['role:admin'])->prefix('admin_panel')->group(function () {
    Route::get('/', [App\Http\Controllers\Admin\HomeController::class, 'index'])
        ->name('homeAdmin');

    Route::resource('category', CategoryController::class);
    Route::resource('image', ImageController::class);
    Route::get('views/image',[ImageController::class, 'views'])->name('image.views');
});
Route::get('image/show',[App\Http\Controllers\ImageController::class, 'show'])->name('image.show');

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Image.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 *
 * @mixin \Eloquent
 * @property string             $img
 * @property string             $title
 * @property string             $text
 * @property int                $category_id
 * @property int                $tag
 * @property Carbon             $created_at
 * @property Carbon             $updated_at
 */


class Image extends Model
{
    use HasFactory;

    protected $table = 'images';

    protected $fillable = [
        'img',
        'title',
        'text',
        'category_id',
        'tag'
    ];

    public function category()
    {
        return $this->belongsTo(Category::class,'category_id','id');
    }
}

app/Http/Controllers/Admin/ImageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\URL;

class ImageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $images = Image::query()
            ->orderBy('created_at','desc')
            ->get();

        return view('admin.image.index', [
            'images' => $images
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::query()
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.image.create', [
            'categories' => $categories
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,
            [
                'photo' => 'image|mimes:jpeg,png,jpg,svg|max:2048',
            ]
        );
        $path = $request->file('photo')->store('/images');
        $image = new Image();
        $image->title = $request->title;
        $image->text = $request->text;
        $image->img = $path;
        $image->category_id = $request->category_id;
        $image->tag = $request->tag;
        $image->save();
        return redirect()->back()->with('success','Категория успешно создана!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function show(Image $image)
    {
        return view('admin.image.show',
        [
            'image' => $image
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function edit(Image $image)
    {
        $categories = Category::query()
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.image.edit', [
            'categories' => $categories,
            'image' => $image,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Image $image)
    {
        $image->img = $request->file;
        $image->title = $request->title;
        $image->text = $request->text;
        $image->category_id = $request->category_id;
        $image->tag = $request->tag;
        $image->save();

        return redirect()->back()->with('success','Категория успешно обновлена!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Image  $image
     * @return \Illuminate\Http\Response
     */
    public function destroy(Image $image)
    {
        $image->delete();

        return redirect()->back()->with('success','Категория успешно была удалена!');
    }

    public function views(Request $request)
    {
        $categories = Category::query()
            ->orderBy('created_at', 'desc')
            ->get();

        $imagesQuery = Image::query()->with('category');
        $category_id = $request->get('category_id');
        $text = $request->get('text');
        $tags = $request->get('tags');

        if ($category_id)
        {
            $imagesQuery->where('category_id', '=', $category_id);
        }
        if ($text)
        {
            $imagesQuery->where('text', 'like', '%' .$text. '%');

        }
        if ($tags)
        {
            $imagesQuery->where('tag', 'like', '%' .$tags. '%');
        }

        $images = $imagesQuery->orderBy('created_at','desc')->get();

        return view('admin.image.views',[
            'images' => $images,
            'categories' => $categories
        ]);
    }
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Image;
use \Illuminate\Http\Request;

class ImageController extends Controller
{
    public function show(Request $request)
    {
        $categories = Category::query()
            ->orderBy('created_at', 'desc')
            ->get();

        $imagesQuery = Image::query()->with('category');
        $category_id = $request->get('category_id');
        $text = $request->get('text');
        $tags = $request->get('tags');

        if ($category_id)
        {
            $imagesQuery->where('category_id', '=', $category_id);
        }
        if ($text)
        {
            $imagesQuery->where('text', 'like', '%' .$text. '%');

        }
        if ($tags)
        {
            $imagesQuery->where('tag', 'like', '%' .$tags. '%');
        }

        $images = $imagesQuery->orderBy('created_at','desc')->simplePaginate('2');;

        return view('image.show',[
            'images' => $images,
            'categories' => $categories
        ]);
    }
}

resources/views/admin/image/create.blade.php
@extends('layouts.admin_layout')

@section('title', 'Добавить изображения')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Добавить изображения</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{ route('image.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Заголовок</label>
                                    <input name="title" type="text" class="form-control" placeholder="Введите заголовок"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label>Описание</label>
                                    <input name="text" type="text" class="form-control" placeholder="Введите описание"
                                           required>
                                </div>
                                <div class="form-group">
                                    <label for="customFile">Изображение</label>
                                    <div class="form-group">
                                        <div class="custom-file">
                                            <input name="photo" type="file" class="custom-file-input" id="customFile">
                                            <label class="custom-file-label" for="customFile">Загрузите изображение</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <!-- select -->
                                    <div class="form-group">
                                        <label>Выберите категорию</label>
                                        <select name="category_id" class="form-control" required>
                                            @foreach ($categories as $category)
                                                <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Тег</label>
                                    <input name="tag" type="text" class="form-control" placeholder="Введите тэг"
                                           required>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <script src="/admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- bs-custom-file-input -->
    <script src="/admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
@endsection

resources/views/admin/image/edit.blade.php
@extends('layouts.admin_layout')

@section('title', 'Редактирование изображения')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Редактирование изображения:</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <!-- /.card-header -->
                        <!-- form start -->
                        <form action="{{ route('image.update', $image['id']) }}" method="POST">
                            @csrf
                            @method('PATCH')
                            <div class="card-body">
                                <div class="form-group">
                                    <label>Заголовок</label>
                                    <input name="title" value="{{$image['title']}}" type="text" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label>Описание</label>
                                    <input name="text" value="{{$image['text']}}" type="text" class="form-control" required>
                                </div>
                                <div class="form-group">
                                    <label for="customFile">Изображение</label>
                                    <div class="form-group">
                                        <div class="custom-file">
                                            <input name="file" type="file" class="custom-file-input" id="customFile">
                                            <label class="custom-file-label" for="customFile">{{$image['img']}}</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label>Категория</label>
                                    <select name="category_id" class="form-control" required>
                                        @foreach ($categories as $category)
                                            <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label>Тэги</label>
                                    <input name="tag" value="{{$image['tag']}}" type="text" class="form-control" required>
                                </div>
                            </div>
                            <div class="card-footer">
                                <button type="submit" class="btn btn-primary">Сохранить</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <script src="/admin/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="/admin/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- bs-custom-file-input -->
    <script src="/admin/plugins/bs-custom-file-input/bs-custom-file-input.min.js"></script>
    <script>
        $(function () {
            bsCustomFileInput.init();
        });
    </script>
    <!-- /.content -->
@endsection

resources/views/admin/image/index.blade.php
@extends('layouts.admin_layout')

@section('title', 'Все изображении')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Все изображении</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th style="width: 5%">
                                ID
                            </th>
                            <th>
                                Заголовок
                            </th>
                            <th>
                                Описание
                            </th>
                            <th>
                                Изображения
                            </th>
                            <th>
                                Категория
                            </th>
                            <th>
                                Тэги
                            </th>
                            <th style="width: 30%">
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach ($images as $image)
                            <tr>
                                <td>
                                    {{ $image['id'] }}
                                </td>
                                <td>
                                    {{ $image['title'] }}
                                </td>
                                <td>
                                    {{ $image['text'] }}
                                </td>
                                <td>
                                    {{ $image['img'] }}
                                </td>
                                <td>
                                    {{ optional($image->category)->name }}
                                </td>
                                <td>
                                    {{ $image['tag'] }}
                                </td>

                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="{{ route('image.show',$image['id']) }}">
                                        <i class="fas fa-eye"></i>
                                        </i>
                                        Просмотр
                                    </a>
                                    <a class="btn btn-info btn-sm" href="{{ route('image.edit', $image['id']) }}">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Редактировать
                                    </a>
                                    @include('admin.image._partarials._form')
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/image/show.blade.php
@extends('layouts.admin_layout')

@section('title', 'Изображения')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Изображения</h1>
                </div><!-- /.col -->
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table table-striped projects">
                        <thead>
                        <tr>
                            <th>
                                Заголовок
                            </th>
                            <th>
                                Описание
                            </th>
                            <th>
                                Изображения
                            </th>
                            <th>
                                Категория
                            </th>
                            <th>
                                Тэги
                            </th>
                            <th style="width: 30%">
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    {{ $image['title'] }}
                                </td>
                                <td>
                                    {{ $image['text'] }}
                                </td>
                                <td>
                                    <img src="{{ Storage::url($image->img)}}" style="height: 240px">
                                </td>
                                <td>
                                    {{ optional($image->category)->name }}
                                </td>
                                <td>
                                    {{ $image['tag'] }}
                                </td>
                                <td></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection

resources/views/admin/image/views.blade.php
@extends('layouts.admin_layout')

@section('title', 'Все изображении')
@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>Изображений</h1>
                </div><!-- /.col -->
                <form method="GET" action="{{route('image.views')}}">
                    <div class="row mb-2">
                        <div class="form-group col-sm-6 col-md-3">
                            <!-- select -->
                            <div class="form-group">
                                <label>Категория</label>
                                <select name="category_id" class="form-control">
                                    @foreach ($categories as $category)
                                        <option value="{{ $category['id'] }}">{{ $category['name'] }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-3">
                            <label for="text">Описание
                                <input type="text" name="text" id="text" size="6" value="{{ request()->text}}">
                            </label>
                            <label for="tags">Тэги
                                <input type="text" name="tags" id="tags" size="6"  value="{{ request()->tags }}">
                            </label>
                        </div>
                        <div class="col-sm-6 col-md-3">
                            <button type="submit" class="btn btn-primary">Применить фильтр</button>
                        </div>
                        <div class="col-sm-6 col-md-3">
                        <a href="{{route('image.views')}}" class="btn btn-warning">Сбросить фильтр</a>
                        </div>
                    </div>
                </form>
            </div><!-- /.row -->
            @if (session('success'))
                <div class="alert alert-success" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i>{{ session('success') }}</h4>
                </div>
            @endif
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="card">
                <div class="card-body p-0">
                    <table class="table">
                        <tbody>
                        @foreach ($images as $image)
                            <tr>
                                <td>
                                   <h3>Изображение</h3>
                                    <p style="font-size: 20px">Заголовок: <strong>{{$image->title}}</strong></p>
                                    <img src="{{ Storage::url($image->img)}}" style="height: 240px">
                                    <p style="font-size: 20px">Описание: <strong>{{$image->text}}</strong></p>
                                    <p style="font-size: 20px">Категория: <strong>  {{ optional($image->category)->name }}</strong></p>
                                    <p style="font-size: 20px">Тэги: <strong>  {{ $image->tag }}</strong></p>
                                </td>
                            </tr>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
@endsection